//! Cross-validation integration test.
//!
//! Reads fixture files generated by `ts-reference/snapshot-obligations.ts`,
//! runs the Rust health evaluation on the raw account data, and compares
//! against the TS SDK reference values.
//!
//! To generate fixtures:
//!   cd ts-reference && npm install && RPC_URL=<your-rpc> npx ts-node snapshot-obligations.ts
//!
//! Then run:
//!   cargo test --test cross_validate_health

use std::fs;
use std::path::Path;

use base64::Engine;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct ObligationFixture {
    pubkey: String,
    raw_account_data_base64: String,
    ts_sdk_values: TsSdkValues,
}

#[derive(Debug, Deserialize)]
struct TsSdkValues {
    loan_to_value: String,
    unhealthy_ltv: String,
    is_liquidatable: bool,
    deposited_value: String,
    borrowed_value_bf_adjusted: String,
    unhealthy_borrow_value: String,
    borrowed_assets_market_value: String,
}

/// Tolerance for floating-point LTV comparison.
/// The TS SDK uses Decimal.js while Rust uses f64, so small deviations are expected.
const LTV_TOLERANCE: f64 = 0.0001;

fn dummy_config() -> liquidation_bot::config::AppConfig {
    liquidation_bot::config::AppConfig {
        rpc_url: String::new(),
        grpc_url: String::new(),
        grpc_token: None,
        kamino_market: "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF".to_string(),
        klend_program_id: "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD".to_string(),
        liquidator_keypair_path: String::new(),
        min_profit_lamports: 0,
        supabase_url: None,
        supabase_service_role_key: None,
    }
}

#[test]
fn validate_health_against_ts_sdk() {
    let fixtures_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");

    if !fixtures_dir.exists() {
        eprintln!(
            "No fixtures directory found at {}. \
             Run `cd ts-reference && npm install && npx ts-node snapshot-obligations.ts` first.",
            fixtures_dir.display()
        );
        return;
    }

    let entries: Vec<_> = fs::read_dir(&fixtures_dir)
        .expect("failed to read fixtures dir")
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .is_some_and(|ext| ext == "json")
        })
        .collect();

    if entries.is_empty() {
        eprintln!("No fixture files found. Skipping cross-validation.");
        return;
    }

    let config = dummy_config();
    let mut pass = 0;
    let mut fail = 0;

    for entry in &entries {
        let content = fs::read_to_string(entry.path()).expect("failed to read fixture");
        let fixture: ObligationFixture =
            serde_json::from_str(&content).expect("failed to parse fixture");

        let raw_data = base64::engine::general_purpose::STANDARD
            .decode(&fixture.raw_account_data_base64)
            .expect("failed to decode base64");

        let result = match liquidation_bot::obligation::health::evaluate(&raw_data, &config) {
            Ok(r) => r,
            Err(e) => {
                eprintln!("FAIL {}: evaluation error: {}", fixture.pubkey, e);
                fail += 1;
                continue;
            }
        };

        // Compare is_liquidatable (boolean — must match exactly)
        if result.is_liquidatable != fixture.ts_sdk_values.is_liquidatable {
            eprintln!(
                "FAIL {} is_liquidatable: rust={} ts={}",
                fixture.pubkey, result.is_liquidatable, fixture.ts_sdk_values.is_liquidatable
            );
            fail += 1;
            continue;
        }

        // Compare LTV values
        let ts_ltv: f64 = fixture.ts_sdk_values.loan_to_value.parse().unwrap_or(0.0);
        let ts_unhealthy_ltv: f64 = fixture.ts_sdk_values.unhealthy_ltv.parse().unwrap_or(0.0);

        if (result.current_ltv - ts_ltv).abs() > LTV_TOLERANCE {
            eprintln!(
                "FAIL {} ltv: rust={:.6} ts={:.6} (delta={:.6})",
                fixture.pubkey,
                result.current_ltv,
                ts_ltv,
                (result.current_ltv - ts_ltv).abs()
            );
            fail += 1;
            continue;
        }

        if (result.unhealthy_ltv - ts_unhealthy_ltv).abs() > LTV_TOLERANCE {
            eprintln!(
                "FAIL {} unhealthy_ltv: rust={:.6} ts={:.6}",
                fixture.pubkey, result.unhealthy_ltv, ts_unhealthy_ltv
            );
            fail += 1;
            continue;
        }

        pass += 1;
    }

    println!(
        "\nCross-validation results: {} passed, {} failed out of {} fixtures",
        pass,
        fail,
        entries.len()
    );

    assert_eq!(fail, 0, "{} fixtures failed cross-validation", fail);
}
